### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by hefee** [sdgathman/pysrs#12]
It would be great to have a new version. The last was in 2017 and several fixing regarding python3 support entered master.
That's why I think releasing a new version makes sense.

And that would fix the [Debian bug #1008829](https://bugs.debian.org/1008829).

**Comment by sdgathman** [comment]
I pushed my latest tag.  I haven't tested thoroughly on python3, so please report problems.  My production mail is still python2.7.
