### ISSUE TITLE
CentOS-7 does not have bsddb3

### ISSUE THREAD

**Issue by sdgathman** [sdgathman/pysrs#2]
Fedora (and apparently Debian) do have bsddb3.  Is there another simple database that would be available in both python2 and python3 on CentOS-7 as well as other distros?

**Comment by hefee** [comment]
why not use the following snipset:
```
try:
    import bsddb3 as bsddb
except ImportError:
    import bsddb
```
because bsddb is only use at one place, so this should work. bsddb was for python2.X inside the core.

**Comment by sdgathman** [comment]
Yes, of course.  But that doesn't help to run pysrs under python3.4 on CentOS-7.  My production mail systems for real-life testing run CentOS-7.  For the time being, I will test running with python2 on EL7, and just run test cases for python3 on Fedora.  Someone else can report any py3 problems in real life.

I might try compiling the Fedora bsddb3 package on EL7.  Often this Just Works.

**Comment by sdgathman** [comment]
I ended up just packaging pysrs for python2 for EL7.   Eventually, bsddb3 may show up in EPEL.
