### ISSUE TITLE
add git tags for ready versions

### ISSUE THREAD

**Issue by hefee** [sdgathman/pysrs#3]
Currently there are no tags for released versions, that makes it hard for Debian to ship the package.
Please add version tags for already released version.

**Comment by sdgathman** [comment]
I added a tag for pysrs-1.0 before merging the python3 PR.  I updated some versions before tagging, and having touched the code, something could have broken - I haven't made and installed a package to fully test.

**Comment by hefee** [comment]
mmh I see. thanks for the tag. Please do releases like this  1.0.4 with that it is easer for packagers to go on. On debian we have the -X as Debian revision. So please use these kind of tags in future. 

If you look at https://tracker.debian.org/pkg/pysrs you can't see what 1.0 tarball was used. that's why it is important that you make tags also for the smaller releases, than i can easily track newer versions. (yes all links are very outdated, currently I'm waiting till you give a first release/prerelease of python3 support, so i can push this to experimental). But take your time!

**Comment by sdgathman** [comment]
@hefee Do you mean you want 3 part versions?  Or that you don't like the name in front of the tag?  I put the name in front of the tag so that pulling the tarball from github gives a properly named archive.
```
https://github.com/sdgathman/pysrs/archive/pysrs-1.0.tar.gz
```
With projects that use bare versions, I have to rename the archive when building packages:

**Comment by hefee** [comment]
no the name in front is not harming Debian packaging, Debian renames it anyways, if it doesn't match.

I mean a 3part version number, because you released 1.0 already (https://sourceforge.net/projects/pymilter/files/pysrs/pysrs-1.0/) and the tag pysrs-1.0 is not the same tarball. And that should be the idea behind tag and tarball, that they are identical :) thats why i think you should add a 3 part...

**Comment by sdgathman** [comment]
Oh right.  Forgot about sourceforge.  Sorry about that.

**Comment by hefee** [comment]
fine for me now.
