### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jaraco** [sdgathman/pysrs#6]
Is there a reason recent releases haven't been made to PyPI? Is there anything I can do to help facilitate a published release?

**Comment by sdgathman** [comment]
pypi won't let me upload a new release, tells me to use "warehouse".  I've been clicking around warehouse, and it tells me to read the Python Packaging Guide to discover the new way.  Apparently I need a new tool called "twine".  Twine won't work without a new format for ~/.pypirc, which has yet another set of docs - and that's were I left it several months ago.  I suppose I'll have to continue threading through the new stuff at some point, but I don't really use pypi anymore.

**Comment by sdgathman** [comment]
Ok, went back to warehouse docs, and finally satisfied "twine".  The latest release is now on pypi.
